openapi: 3.0.3
info:
  title: Air Quality API v0.1
  description: |-
    This is a simple swagger API documentation around the Air quality API server.
  version: v0.1
servers:
  - url: http://localhost:8050
tags:
  - name: Air readings
    description: Operations that control the air readings
paths:
  /air-quality:
    get:
      tags:
        - Air readings
      summary: Fetch current air quality readings.
      description: Fetch current air quality readings.
      operationId: getAirQuality
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AirQuality'
        '500':
          description: Fetch failed
  /lcd-screen:
    post:
      tags:
        - Air readings
      summary: Change the LCD screen display on the enviro sensor.
      description: Change the LCD screen display on the enviro sensor.
      operationId: postLCDScreen
      requestBody:
        description: What to change the LCD screen to.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LCDScreenRequest'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GeneralResponse'
        '400':
          description: Bad request body
        '500':
          description: Stop failed
components:
  schemas:
    AirQuality:
      type: object
      properties:
        sensors:
          type: object
          properties:
            light:
              $ref: '#/components/schemas/SensorReading'
            hazardous_gases:
              $ref: '#/components/schemas/HazardousGases'
            humidity:
              $ref: '#/components/schemas/SensorReading'
            pressure:
              $ref: '#/components/schemas/SensorReading'
            temperature:
              $ref: '#/components/schemas/SensorReading'
        current_time:
          type: string
    HazardousGases:
      type: object
      properties:
        oxidised:
          $ref: '#/components/schemas/SensorReading'
        reduced:
          $ref: '#/components/schemas/SensorReading'
        nh3:
          $ref: '#/components/schemas/SensorReading'
    SensorReading:
      type: object
      properties:
        value:
          type: number
        unit:
          type: string
    LCDScreenRequest:
      type: object
      properties:
        display:
          type: string
          enum:
            - IP_address
            - temperature
            - image_processing
    GeneralResponse:
      type: object
      properties:
        status:
          type: string