'''The file will hold the constants used throughout the air quality.'''
SHOW_IP_ADDRESS = "IP_address"
SHOW_TEMPERATURE = "temperature"
SHOW_IMAGE_PROCESSING = "image_processing"

ACCEPTABLE_LCD_DISPLAYS = [SHOW_IP_ADDRESS, SHOW_TEMPERATURE, SHOW_IMAGE_PROCESSING]

BASELINE_OXIDISING = 26.13
BASELINE_REDUCING = 255.11
BASELINE_NH3 = 368.83

PPM = "ppm"
