'''The file will hold the constants used throughout the air quality.'''
SHOW_IP_ADDRESS = "IP_address"
SHOW_TEMPERATURE = "temperature"
SHOW_IMAGE_PROCESSING = "image_processing"

ACCEPTABLE_LCD_DISPLAYS = [SHOW_IP_ADDRESS, SHOW_TEMPERATURE, SHOW_IMAGE_PROCESSING]

BASELINE_OXIDISING = 120.73
BASELINE_REDUCING = 342.84
BASELINE_NH3 = 652.48

PPM = "ppm"
